=== sumitkumarpaul/bidirectional_privacy/poc/xmlrss/testdata/pc.dtd
<!--
  ~ XMLRSS - A Java Crypto Provider for Redactable Signatures and their
  ~ XML Signature encoding.
  ~
  ~ Copyright (c) 2017 Wolfgang Popp
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!ELEMENT PC (PDS | DH | SC | VK | Signature)+>
<!ELEMENT PDS (PD)+>
<!ELEMENT PD (S | CH | AS)+>
<!ELEMENT S (#PCDATA)>
<!ELEMENT CH (#PCDATA)>
<!ELEMENT AS (#PCDATA)>
<!ELEMENT DH (#PCDATA)>
<!ELEMENT SC (#PCDATA)>
<!ELEMENT VK (#PCDATA)>

<!ELEMENT Signature (SignatureInfo | References | SignatureValue )+>
<!ELEMENT SignatureInfo ( CanonicalizationMethod | RedactableSignatureAlgorithm )+>
<!ELEMENT CanonicalizationMethod (#PCDATA)>
<!ELEMENT RedactableSignatureAlgorithm (#PCDATA)>
<!ELEMENT References (Reference)+>
<!ELEMENT Reference (Pointer | Proof )+>
<!ELEMENT Pointer (#PCDATA)>
<!ELEMENT Proof (Data)+>
<!ELEMENT Data (#PCDATA)>
<!ELEMENT SignatureValue ( Tag | ProofOfTag | AccumulatorValue )+>
<!ELEMENT Tag (#PCDATA)>
<!ELEMENT ProofOfTag (#PCDATA)>
<!ELEMENT AccumulatorValue (#PCDATA)>

<!ATTLIST PC id ID #IMPLIED>
<!ATTLIST PDS id ID #IMPLIED>
<!ATTLIST Signature xmlns CDATA #IMPLIED>
<!ATTLIST PD id ID #IMPLIED>
<!ATTLIST DH id ID #IMPLIED>
<!ATTLIST SC id ID #IMPLIED>
<!ATTLIST VK id ID #IMPLIED>

<!ATTLIST CanonicalizationMethod Algorithm CDATA #IMPLIED>
<!ATTLIST RedactableSignatureAlgorithm Algorithm CDATA #IMPLIED>
<!ATTLIST Pointer Redactable CDATA #IMPLIED>
<!ATTLIST Pointer URI CDATA #IMPLIED>

=== sumitkumarpaul/bidirectional_privacy/poc/xmlrss/testdata/pc_1.xml
<?xml version="1.0"?>
<!DOCTYPE PC SYSTEM "xmlrss/testdata/pc.dtd">
<PC id="pc">
    <PDS id="pds">
        <PD id="pd_1">
            <S>OE5T4dEw2EvOgFIoaIEURe3LqWMj1heOJqDlrNxTXn6yhGpwk8nwl1Rzb4DlDr3RSerocSyDTfOeh3YLlV9EcfNX96vnWsWXKJBl51LJsMth3wPRcL0ZCO4wdOh05kAR5MDGrCJjkyNcGbES8F8UCWtHuhXuBcwv2eXTv5LHXQ5qkis58pmB7ac2E1USIuNOPPErFWpLMI7EOMCB6gASJFyoTUmVnfW6ENOLjFq0hFZih5tHbIeJb6FLWNa8pp5fVMCxRFKxVMetWsPxo5kFtWBcRsjRUBmUCDggWTUdYdFBoQqSMq3yLh54sG45TVLBbGNqFLrNmpXF0QpMc7klTG9uOIF24n1k9ONClJM3mqYh2Nh38Lya4Qs4AnUANQD00bVZJ9VTMppBQq7uHoqfnUPER3HFbYCWOcB28JJPAqQNuV1bZucalbzL2JlEBItyGLx2SapgJ9V2qdv0UCY0skiuLZ4ypQrRzyyIxkhdX1Mgbhuzshuy</S>
            <CH>2f0060873d9c9c30ca4df80a9e9b5f8c172fb8fc14fba2bd6dee465ed8123b43</CH>
            <AS>IAG3pv4ARIZuEnMSaO/9Rsals6tsN0Uoyia8F4pOW0cFjgjs1Bwiembo64nrvA8f6FyXomK0rPBkEfbYvOT7FxVq/Hal0eDauSdcRCAVB2tbKJcUfgm3tuENy588+7QxnN8RjMx928SyqWnArRisLAIgAd4hF0gOYuAgohUJ39qnBpZ0e0tHO3MhZUbEfjy7/iAbDfgs1Q8IszVYXhBK9KYV03ncRJj+GOHWn8tEz1jcDJ9z5MxPjXva3xmNNMtDKu55EtQczg5UOXfUxOboPc0oeZk2zyJYRlU2SQWTDqhfgKiJTMqb0qONp8VlJVulBMJpTouB1fcicfQgTrQQCQ==</AS>
        </PD>
    </PDS>
    <DH id="dh"></DH>
    <SC id="sc"></SC>
    <VK id="vk"></VK>
</PC>
