=== sumitkumarpaul/bidirectional_privacy/poc/xmlrss/testdata/vehicles.dtd
<!--
  ~ XMLRSS - A Java Crypto Provider for Redactable Signatures and their
  ~ XML Signature encoding.
  ~
  ~ Copyright (c) 2017 Wolfgang Popp
  ~
  ~ This program is free software: you can redistribute it and/or modify
  ~ it under the terms of the GNU General Public License as published by
  ~ the Free Software Foundation, either version 3 of the License, or
  ~ (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program.  If not, see <http://www.gnu.org/licenses/>.
  -->

<!ELEMENT Vehicle (Aircraft | Watercraft | MotorVehicles | Signature)+>
<!ELEMENT Aircraft (Glider | Jet)+>
<!ELEMENT Watercraft (Sailboat | Motorboat)+>
<!ELEMENT MotorVehicles (Car | Motorcycle)+>
<!ELEMENT Glider (#PCDATA)>
<!ELEMENT Jet (#PCDATA)>
<!ELEMENT Motorboat (#PCDATA)>
<!ELEMENT Sailboat (#PCDATA)>
<!ELEMENT Motorcycle (#PCDATA)>
<!ELEMENT Car (#PCDATA)>
<!ELEMENT Signature ANY>

<!ATTLIST Aircraft id ID #IMPLIED>
<!ATTLIST Watercraft id ID #IMPLIED>
<!ATTLIST MotorVehicles id ID #IMPLIED>
<!ATTLIST Jet id ID #IMPLIED>
<!ATTLIST Glider id ID #IMPLIED>
<!ATTLIST Car Brand CDATA #REQUIRED
        Model CDATA #REQUIRED>
<!ATTLIST Motorcycle Brand CDATA #REQUIRED
        Model CDATA #REQUIRED>

=== sumitkumarpaul/bidirectional_privacy/poc/xmlrss/testdata/vehicles.xml
<?xml version="1.0"?>
<!DOCTYPE Vehicle SYSTEM "testdata/vehicles.dtd">
<Vehicle>
    <Aircraft id="a1">
        <Glider id="g1">DG-800</Glider>
        <Jet id="j1">Airbus A380</Jet>
    </Aircraft>
    <Watercraft id="a2">
        <Sailboat>Bavaria 36</Sailboat>
        <Motorboat>Bavaria Sport 29</Motorboat>
    </Watercraft>
    <MotorVehicles id="a3">
        <Car Model="A3" Brand="Audi"/>
        <Car Brand="Audi" Model="A4"/>
        <Car Brand="BMW" Model="i7"/>
        <Motorcycle Brand="Honda" Model="RC212V"/>
    </MotorVehicles>
</Vehicle>
